import { Providers } from "@/components/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "@/components/Toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={"min-h-screen p-4"}>
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
